// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	ChatMessage
	User
	Message
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMessage_RequestType int32

const (
	ChatMessage_USER_CHAT  ChatMessage_RequestType = 0
	ChatMessage_USER_JOIN  ChatMessage_RequestType = 1
	ChatMessage_USER_LEAVE ChatMessage_RequestType = 2
)

var ChatMessage_RequestType_name = map[int32]string{
	0: "USER_CHAT",
	1: "USER_JOIN",
	2: "USER_LEAVE",
}
var ChatMessage_RequestType_value = map[string]int32{
	"USER_CHAT":  0,
	"USER_JOIN":  1,
	"USER_LEAVE": 2,
}

func (x ChatMessage_RequestType) String() string {
	return proto.EnumName(ChatMessage_RequestType_name, int32(x))
}
func (ChatMessage_RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ChatMessage struct {
	Type    ChatMessage_RequestType `protobuf:"varint,1,opt,name=type,enum=chat.ChatMessage_RequestType" json:"type,omitempty"`
	User    *User                   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Message *Message                `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetType() ChatMessage_RequestType {
	if m != nil {
		return m.Type
	}
	return ChatMessage_USER_CHAT
}

func (m *ChatMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type User struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Message struct {
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "chat.ChatMessage")
	proto.RegisterType((*User)(nil), "chat.User")
	proto.RegisterType((*Message)(nil), "chat.Message")
	proto.RegisterEnum("chat.ChatMessage_RequestType", ChatMessage_RequestType_name, ChatMessage_RequestType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChatService service

type ChatServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (ChatService_StreamClient, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (ChatService_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChatService_serviceDesc.Streams[0], c.cc, "/chat.ChatService/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceStreamClient{stream}
	return x, nil
}

type ChatService_StreamClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatServiceStreamClient struct {
	grpc.ClientStream
}

func (x *chatServiceStreamClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceStreamClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChatService service

type ChatServiceServer interface {
	Stream(ChatService_StreamServer) error
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Stream(&chatServiceStreamServer{stream})
}

type ChatService_StreamServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatServiceStreamServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceStreamServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ChatService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4b, 0x4b, 0xfb, 0x40,
	0x14, 0xc5, 0x3b, 0xfd, 0x87, 0xe6, 0x9f, 0x1b, 0x5a, 0xe2, 0x5d, 0x85, 0x82, 0x52, 0xc6, 0x85,
	0x59, 0x05, 0x8d, 0xee, 0x5c, 0x95, 0x10, 0x50, 0xf1, 0x01, 0x93, 0xd6, 0xad, 0x8c, 0xe1, 0x62,
	0x5d, 0xe4, 0xe1, 0xcc, 0x54, 0xe8, 0x17, 0xf4, 0x73, 0x49, 0x66, 0x4c, 0x29, 0x74, 0x37, 0xe7,
	0xce, 0xef, 0xdc, 0xc7, 0x01, 0xa8, 0x36, 0xd2, 0xa4, 0x9d, 0x6a, 0x4d, 0x8b, 0x5e, 0xff, 0xe6,
	0x3f, 0x0c, 0xc2, 0x7c, 0x23, 0xcd, 0x13, 0x69, 0x2d, 0x3f, 0x08, 0xaf, 0xc0, 0x33, 0xbb, 0x8e,
	0x62, 0xb6, 0x60, 0xc9, 0x2c, 0x3b, 0x4d, 0xad, 0xe1, 0x00, 0x48, 0x05, 0x7d, 0x6d, 0x49, 0x9b,
	0xd5, 0xae, 0x23, 0x61, 0x51, 0x3c, 0x03, 0x6f, 0xab, 0x49, 0xc5, 0xe3, 0x05, 0x4b, 0xc2, 0x0c,
	0x9c, 0x65, 0xad, 0x49, 0x09, 0x5b, 0xc7, 0x0b, 0xf0, 0x6b, 0x67, 0x8e, 0xff, 0x59, 0x64, 0xea,
	0x90, 0xbf, 0x8e, 0x62, 0xf8, 0xe5, 0xb7, 0x10, 0x1e, 0x74, 0xc7, 0x29, 0x04, 0xeb, 0xb2, 0x10,
	0x6f, 0xf9, 0xdd, 0x72, 0x15, 0x8d, 0xf6, 0xf2, 0xe1, 0xe5, 0xfe, 0x39, 0x62, 0x38, 0x03, 0xb0,
	0xf2, 0xb1, 0x58, 0xbe, 0x16, 0xd1, 0x98, 0x73, 0xf0, 0xfa, 0x99, 0x38, 0x87, 0xff, 0xfd, 0xd4,
	0x46, 0xd6, 0xee, 0x88, 0x40, 0xec, 0x35, 0x3f, 0x07, 0x7f, 0xb8, 0x33, 0x06, 0xbf, 0x6a, 0x1b,
	0x43, 0x8d, 0xb1, 0x7b, 0x07, 0x62, 0x90, 0x59, 0xee, 0x02, 0x29, 0x49, 0x7d, 0x7f, 0x56, 0x84,
	0x37, 0x30, 0x29, 0x8d, 0x22, 0x59, 0xe3, 0xc9, 0x51, 0x18, 0xf3, 0xe3, 0x12, 0x1f, 0x25, 0xec,
	0x92, 0xbd, 0x4f, 0x6c, 0xc6, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x7b, 0x4f, 0x25,
	0x71, 0x01, 0x00, 0x00,
}
