// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	ChatMessage
	User
	Message
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_MESSAGE Message_Type = 0
	Message_ERROR   Message_Type = 1
)

var Message_Type_name = map[int32]string{
	0: "MESSAGE",
	1: "ERROR",
}
var Message_Type_value = map[string]int32{
	"MESSAGE": 0,
	"ERROR":   1,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ChatMessage struct {
	Register bool     `protobuf:"varint,1,opt,name=register" json:"register,omitempty"`
	User     *User    `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Message  *Message `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetRegister() bool {
	if m != nil {
		return m.Register
	}
	return false
}

func (m *ChatMessage) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatMessage) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type User struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Message struct {
	Type    Message_Type `protobuf:"varint,1,opt,name=type,enum=chat.Message_Type" json:"type,omitempty"`
	Content string       `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_MESSAGE
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "chat.ChatMessage")
	proto.RegisterType((*User)(nil), "chat.User")
	proto.RegisterType((*Message)(nil), "chat.Message")
	proto.RegisterEnum("chat.Message_Type", Message_Type_name, Message_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ChatService service

type ChatServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (ChatService_StreamClient, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (ChatService_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ChatService_serviceDesc.Streams[0], c.cc, "/chat.ChatService/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceStreamClient{stream}
	return x, nil
}

type ChatService_StreamClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatServiceStreamClient struct {
	grpc.ClientStream
}

func (x *chatServiceStreamClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceStreamClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ChatService service

type ChatServiceServer interface {
	Stream(ChatService_StreamServer) error
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Stream(&chatServiceStreamServer{stream})
}

type ChatService_StreamServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatServiceStreamServer struct {
	grpc.ServerStream
}

func (x *chatServiceStreamServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceStreamServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _ChatService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat.proto",
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xed, 0xfe, 0x7e, 0x6b, 0xd3, 0x4c, 0x50, 0xea, 0x9c, 0x42, 0x0f, 0xa5, 0xec, 0x41, 0x73,
	0x0a, 0x12, 0xfd, 0x02, 0x52, 0x82, 0xa7, 0x22, 0x4c, 0xf4, 0x03, 0xac, 0x61, 0x68, 0x8b, 0xe4,
	0x0f, 0xbb, 0xab, 0xd0, 0x6f, 0x2f, 0xbb, 0x6b, 0x8a, 0xe2, 0x6d, 0xde, 0xcc, 0x9b, 0xf7, 0x1e,
	0x0f, 0xa0, 0x3d, 0x68, 0x57, 0x8e, 0x66, 0x70, 0x03, 0x4a, 0x3f, 0x2b, 0x03, 0xd9, 0xf6, 0xa0,
	0xdd, 0x8e, 0xad, 0xd5, 0x7b, 0xc6, 0x15, 0x2c, 0x0c, 0xef, 0x8f, 0xd6, 0xb1, 0xc9, 0xc5, 0x46,
	0x14, 0x0b, 0x3a, 0x63, 0x5c, 0x83, 0xfc, 0xb0, 0x6c, 0xf2, 0x7f, 0x1b, 0x51, 0x64, 0x15, 0x94,
	0x41, 0xeb, 0xd5, 0xb2, 0xa1, 0xb0, 0xc7, 0x5b, 0x48, 0xba, 0x28, 0x93, 0xff, 0x0f, 0x94, 0xcb,
	0x48, 0xf9, 0xd6, 0xa6, 0xe9, 0xaa, 0x14, 0x48, 0xff, 0xe6, 0xcd, 0xfc, 0x63, 0xaf, 0x3b, 0x0e,
	0x66, 0x29, 0x9d, 0xb1, 0x7a, 0x87, 0x64, 0xca, 0x74, 0x03, 0xd2, 0x9d, 0xc6, 0x48, 0xb9, 0xaa,
	0xf0, 0x97, 0x68, 0xf9, 0x72, 0x1a, 0x99, 0xc2, 0x1d, 0x73, 0x48, 0xda, 0xa1, 0x77, 0xdc, 0xbb,
	0x10, 0x31, 0xa5, 0x09, 0xaa, 0x35, 0x48, 0xcf, 0xc3, 0x0c, 0x92, 0x5d, 0xdd, 0x34, 0x8f, 0x4f,
	0xf5, 0x72, 0x86, 0x29, 0x5c, 0xd4, 0x44, 0xcf, 0xb4, 0x14, 0xd5, 0x36, 0x96, 0xd0, 0xb0, 0xf9,
	0x3c, 0xb6, 0x8c, 0x0f, 0x30, 0x6f, 0x9c, 0x61, 0xdd, 0xe1, 0x75, 0x34, 0xfb, 0xd1, 0xd0, 0xea,
	0xef, 0x4a, 0xcd, 0x0a, 0x71, 0x27, 0xde, 0xe6, 0xa1, 0xd6, 0xfb, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe2, 0xbd, 0x1e, 0x2b, 0x64, 0x01, 0x00, 0x00,
}
